saga
eyakauleva/ticket-microservice pull request #19
Opened 2023-04-07 14:51 UTC by eyakauleva

close #18

2023-04-09 07:14 UTC, h1alexbel requested changes

2023-04-09 07:14 UTC, h1alexbel commented on src/main/java/com/solvd/micro9/tickets/domain/command/SetTicketsUserIdToNullByUserIdCommand.java
> +public class SetTicketsUserIdToNullByUserIdCommand {
this name is too complex IMO

consider more elegant naming for you classes

2023-04-09 07:14 UTC, h1alexbel commented on src/main/java/com/solvd/micro9/tickets/messaging/KfConsumer.java
> +                        ProcessTicketUpdateCommand command = new ProcessTicketUpdateCommand(
line is too long

2023-04-09 07:14 UTC, h1alexbel commented on src/main/java/com/solvd/micro9/tickets/messaging/KfConsumer.java
> +                        SetTicketsUserIdToNullByUserIdCommand command = new SetTicketsUserIdToNullByUserIdCommand(
line is too long, split it, please

2023-04-09 07:14 UTC, h1alexbel commented on src/main/java/com/solvd/micro9/tickets/service/impl/EsTicketCommandHandlerImpl.java
> +        while (!isStreamCompleted[0]) {
@eyakauleva check #20

2023-04-09 07:14 UTC, h1alexbel commented on src/main/java/com/solvd/micro9/tickets/service/impl/EsTicketCommandHandlerImpl.java
> +
remove empty lines

2023-04-09 07:14 UTC, h1alexbel commented on src/main/java/com/solvd/micro9/tickets/service/impl/EsTicketCommandHandlerImpl.java
> +
remove empty lines

2023-04-09 07:14 UTC, h1alexbel commented on src/main/java/com/solvd/micro9/tickets/service/impl/EsTicketCommandHandlerImpl.java
> +                .subscribe();
you subscribes in this mehtod twicely, that's not good practice
[first](
https://github.com/eyakauleva/ticket-microservice/pull/19/files#diff-d8d3b07fee98e5459b29350f259b5ca997b336a07aeb16e3c0fdab0befaa1e29R107) and now

2023-04-10 09:17 UTC, eyakauleva commented on src/main/java/com/solvd/micro9/tickets/domain/command/SetTicketsUserIdToNullByUserIdCommand.java
> +public class SetTicketsUserIdToNullByUserIdCommand {
fixed 9099b38

2023-04-10 09:17 UTC, eyakauleva commented on src/main/java/com/solvd/micro9/tickets/messaging/KfConsumer.java
> +                        ProcessTicketUpdateCommand command = new ProcessTicketUpdateCommand(
fixed 9099b38

2023-04-10 09:17 UTC, eyakauleva commented on src/main/java/com/solvd/micro9/tickets/messaging/KfConsumer.java
> +                        SetTicketsUserIdToNullByUserIdCommand command = new SetTicketsUserIdToNullByUserIdCommand(
fixed 9099b38

2023-04-10 09:17 UTC, eyakauleva commented on src/main/java/com/solvd/micro9/tickets/service/impl/EsTicketCommandHandlerImpl.java
> +
fixed 9099b38

2023-04-10 09:17 UTC, eyakauleva commented on src/main/java/com/solvd/micro9/tickets/service/impl/EsTicketCommandHandlerImpl.java
> +
fixed 9099b38

2023-04-10 10:10 UTC, h1alexbel approved these changes

2023-04-10 10:10 UTC, merged